swagger: "2.0"
info:
  title: Integrasys API
  version: 1.0.0
host: integrasys.quito.gob.ec
basePath: /api
schemes:
  - https
paths:
  /persona/general:
    get:
      summary: Obtener personas por cédula
      responses:
        '200':
          description: OK
