openapi: 3.0.3
info:
  title: Integrasys API
  version: 1.0.0
servers:
  - url: https://integrasys.quito.gob.ec/api
paths:
  /persona/general:
    get:
      summary: Obtener personas por cédula
      responses:
        '200':
          description: OK
