apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: integrasys-backend      # Nombre único para este componente
  description: Backend que provee la API Integrasys
  owner: roberto.maldonado@quito.gob.ec
spec:
  type: service                 # Puede ser "service", "library", etc.
  lifecycle: production
  providesApis:
    - integrasys-api           
