apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: integrasys-api
  description: API pública de Integrasys para consulta de personas
  tags:
    - integrasys
    - personas
    - gobierno
spec:
  type: openapi
  lifecycle: production
  owner: juan.maldonado@example.com
  definition: https://raw.githubusercontent.com/roberto-ma/MSP/dev/ms-rct-paciente/api-prueba.yaml
