apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: integrasys-api
  description: API pública de Integrasys
spec:
  type: openapi
  lifecycle: production
  owner: juan.perez@example.com
  definition: https://integrasys.quito.gob.ec/api/openapi.yaml
