apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: integrasys-api
  description: API publica de Integrasys (Integración de sistemas)
  links:
    - url: https://integrasys.quito.gob.ec/api
      title: Documentación Swagger
      icon: docs
    - url: https://integrasys.quito.gob.ec
      title: Entorno Productivo
      icon: web
  tags:
   - personas
   - autenticacion

spec:
  type: openapi
  lifecycle: production
  system: integrasys
  owner: roberto.maldonado@quito.gob.ec
  definition: |
    openapi: 3.0.3
    info:
      title: Integrasys API
      version: 1.0.0
      description: API para consulta de personas
    servers:
      - url: https://integrasys.quito.gob.ec
        description: API Integrasys
    paths:
      /persona/general/{identificacionPersona}:
        get:
          summary: Obtener personas por cedula
          parameters:
            - name: identificacionPersona
              in: path
              required: true
              description: "Numero de identificacion de la persona"
              schema:
                type: string
                example: "0603005299"
          responses:
            '200':
              description: Persona encontrada
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      success:
                        type: boolean
                        example: true
                      data:
                        type: object
                        properties:
                          identificacionPersona:
                            type: string
                            example: "0603005299"
                          nombres:
                            type: string
                            example: "Juan Carlos"
                          apellidos:
                            type: string
                            example: "Perez Gonzalez"
                      message:
                        type: string
                        example: "Consulta exitosa"
          security:
            - BearerAuth: []
      /auth/login:
        post:
          summary: Genera el Token
          requestBody:
            required: true
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    usuario:
                      type: string
                      example: "usuario-int"
                    contrasena:
                      type: string
                      example: "Pxxxx_148"
          responses:
            '201':
              description: Token generado exitosamente
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      access_token:
                        type: string
                        example: "string"
                      expires_in:
                        type: integer
                        example: 0
                      refresh_expires_in:
                        type: integer
                        example: 0
                      refresh_token:
                        type: string
                        example: "string"
                      token_type:
                        type: string
                        example: "string"
                      not-before-policy:
                        type: integer
                        example: 0
                      session_state:
                        type: string
                        example: "string"
                      scope:
                        type: string
                        example: "string"
          security: []  # No requiere autenticación para login
    components:
      securitySchemes:
        ApiKeyAuth:
          type: apiKey
          in: header
          name: X-API-Key
        BearerAuth:
          type: http
          scheme: bearer
          bearerFormat: JWT
    security:
      - BearerAuth: []
