apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: integrasys-api
  description: API pública de Integrasys
spec:
  type: openapi
  lifecycle: production
  owner: juan.perez@example.com
  definition: https://raw.githubusercontent.com/roberto-ma/MSP/dev/ms-rct-paciente/api-prueba.yaml
Paso 4: Importa ese archivo catalog-info.yaml en Backstage
