apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: integrasys-api
  description: API publica de Integrasys
spec:
  type: openapi
  lifecycle: production
  owner: juan.maldonado@example.com
  definition: |
    openapi: 3.0.3
    info:
      title: Integrasys API
      version: 1.0.0
      description: API para consulta de personas
    servers:
      - url: /api/proxy/integrasys-api
        description: API Integrasys via proxy de Backstage
    paths:
      /persona/{identificacionPersona}:
        get:
          summary: Obtener personas por cedula
          parameters:
            - name: identificacionPersona
              in: path
              required: true
              description: "Numero de identificacion de la persona"
              schema:
                type: string
                example: "0603005299"
          responses:
            '200':
              description: Persona encontrada
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      success:
                        type: boolean
                        example: true
                      data:
                        type: object
                        properties:
                          identificacionPersona:
                            type: string
                            example: "1234567890"
                          nombres:
                            type: string
                            example: "Juan Carlos"
                          apellidos:
                            type: string
                            example: "Perez Gonzalez"
                      message:
                        type: string
                        example: "Consulta exitosa"
            '400':
              description: Parametros invalidos
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      success:
                        type: boolean
                        example: false
                      error:
                        type: string
                        example: "Parametros invalidos"
            '404':
              description: Persona no encontrada
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      success:
                        type: boolean
                        example: false
                      error:
                        type: string
                        example: "Persona no encontrada"
    components:
      securitySchemes:
        ApiKeyAuth:
          type: apiKey
          in: header
          name: X-API-Key
        BearerAuth:
          type: http
          scheme: bearer
