apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: integrasys-api
  description: API pública de Integrasys
spec:
  type: swagger
  lifecycle: production
  owner: juan.maldonado@example.com
  definition: https://github.com/roberto-ma/MSP/blob/dev/ms-rct-paciente/api-prueba.yaml
